[project]
name = "zetakit"
version = "0.1.0"
description = "Zeta's Quant Tool Kit"
authors = [{name = "Zeta"}]
readme = "README.md"
license = "MIT"
requires-python = ">=3.9"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"